version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: games-library-project
    environment:
      POSTGRES_DB: games-library
      POSTGRES_USER: library-admin
      POSTGRES_PASSWORD: useradmin
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
